### ISSUE TITLE
hockeypuck crash

### ISSUE THREAD

**Issue by bjmgeek** [hockeypuck/server#14] opened 2015-08-01 23:04 UTC
hockeypuck@hockeypuck:~$ /usr/local/bin/hockeypuck -config=/etc/hockeypuck/hockeypuck.conf
WARN[0000] error executing "ALTER TABLE keys ADD CONSTRAINT keys_pk PRIMARY KEY (rfingerprint);": pq: multiple primary keys for table "keys" are not allowed
WARN[0000] error executing "ALTER TABLE keys ADD CONSTRAINT keys_md5 UNIQUE (md5);": pq: relation "keys_md5" already exists
WARN[0000] error executing "CREATE INDEX keys_rfp ON keys(rfingerprint text_pattern_ops);": pq: relation "keys_rfp" already exists
WARN[0000] error executing "CREATE INDEX keys_ctime ON keys (ctime);": pq: relation "keys_ctime" already exists
WARN[0000] error executing "CREATE INDEX keys_mtime ON keys (mtime);": pq: relation "keys_mtime" already exists
WARN[0000] error executing "CREATE INDEX keys_keywords ON keys USING gin(keywords);": pq: relation "keys_keywords" already exists
WARN[0000] error executing "ALTER TABLE subkeys ADD CONSTRAINT subkeys_pk PRIMARY KEY (rsubfp);": pq: multiple primary keys for table "subkeys" are not allowed
WARN[0000] error executing "ALTER TABLE subkeys ADD CONSTRAINT subkeys_fk FOREIGN KEY (rfingerprint) REFERENCES keys(rfingerprint);": pq: constraint "subkeys_fk" for relation "subkeys" already exists
WARN[0000] error executing "CREATE INDEX subkeys_rfp ON subkeys(rsubfp text_pattern_ops);": pq: relation "subkeys_rfp" already exists
2015/08/01 16:06:20 http: multiple response.WriteHeader calls
2015/08/01 17:06:18 http: multiple response.WriteHeader calls
2015/08/01 18:06:03 http: multiple response.WriteHeader calls
2015/08/01 19:06:13 http: multiple response.WriteHeader calls
panic: tomb.Go called after all goroutines terminated

goroutine 22 [running]:
gopkg.in/tomb%2ev2.(*Tomb).Go(0xc2095ea720, 0xc2095ea810)
        /home/bminton/src/hockeypuck/packaging/src/gopkg.in/tomb.v2/tomb.go:145 +0xef
gopkg.in/hockeypuck/conflux.v2/recon.(*Peer).handleConfig(0xc208108380, 0x7fa0ab74f7b0, 0xc2100c2d68, 0xa416f0, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/bminton/src/hockeypuck/packaging/src/gopkg.in/hockeypuck/conflux.v2/recon/peer.go:374 +0x4e3
gopkg.in/hockeypuck/conflux.v2/recon.(*Peer).InitiateRecon(0xc208108380, 0x7fa0ab74f750, 0xc2095ea2a0, 0x0, 0x0)
        /home/bminton/src/hockeypuck/packaging/src/gopkg.in/hockeypuck/conflux.v2/recon/gossip.go:113 +0x2ef
gopkg.in/hockeypuck/conflux.v2/recon.(*Peer).Gossip(0xc208108380, 0x0, 0x0)
        /home/bminton/src/hockeypuck/packaging/src/gopkg.in/hockeypuck/conflux.v2/recon/gossip.go:59 +0x6b9
gopkg.in/hockeypuck/conflux.v2/recon.*Peer.GossipÂ·fm(0x0, 0x0)
        /home/bminton/src/hockeypuck/packaging/src/gopkg.in/hockeypuck/conflux.v2/recon/peer.go:133 +0x39
gopkg.in/tomb%2ev2.(*Tomb).run(0xc2081083a8, 0xc2080e19f0)
        /home/bminton/src/hockeypuck/packaging/src/gopkg.in/tomb.v2/tomb.go:153 +0x24
created by gopkg.in/tomb%2ev2.(*Tomb).Go
        /home/bminton/src/hockeypuck/packaging/src/gopkg.in/tomb.v2/tomb.go:149 +0x119

goroutine 1 [chan receive, 227 minutes]:
gopkg.in/tomb%2ev2.(*Tomb).Wait(0xc2080460d0, 0x0, 0x0)
        /home/bminton/src/hockeypuck/packaging/src/gopkg.in/tomb.v2/tomb.go:116 +0x61
github.com/hockeypuck/server.(*Server).Wait(0xc208046090, 0x0, 0x0)
        /home/bminton/src/hockeypuck/packaging/src/github.com/hockeypuck/server/server.go:285 +0x46
main.main()
        /home/bminton/src/hockeypuck/packaging/src/github.com/hockeypuck/server/cmd/hockeypuck/main.go:68 +0x5fc

goroutine 5 [syscall, 228 minutes]:
os/signal.loop()
        /usr/lib/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.initÂ·1
        /usr/lib/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 6 [chan receive, 228 minutes]:
database/sql.(*DB).connectionOpener(0xc2080a2fa0)
        /usr/lib/go/src/database/sql/sql.go:589 +0x4c
created by database/sql.Open
        /usr/lib/go/src/database/sql/sql.go:452 +0x31c

goroutine 17 [syscall, 228 minutes, locked to thread]:
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 7 [select]:
github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0xc2081080e0)
        /home/bminton/src/hockeypuck/packaging/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:205 +0x21e
created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
        /home/bminton/src/hockeypuck/packaging/src/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:236 +0x24c

goroutine 9 [select, 5 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0xc2080e82c0)
        /home/bminton/src/hockeypuck/packaging/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:120 +0x48c
created by github.com/syndtr/goleveldb/leveldb.openDB
        /home/bminton/src/hockeypuck/packaging/src/github.com/syndtr/goleveldb/leveldb/db.go:126 +0x849

goroutine 10 [select]:
github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc2080e82c0)
        /home/bminton/src/hockeypuck/packaging/src/github.com/syndtr/goleveldb/leveldb/db_state.go:73 +0x14a
created by github.com/syndtr/goleveldb/leveldb.openDB
        /home/bminton/src/hockeypuck/packaging/src/github.com/syndtr/goleveldb/leveldb/db.go:127 +0x863

goroutine 11 [syscall]:
syscall.Syscall(0x4a, 0x3d, 0x0, 0x0, 0x200119, 0x30a4, 0x0)
        /usr/lib/go/src/syscall/asm_linux_amd64.s:21 +0x5
syscall.Fsync(0x3d, 0x0, 0x0)
        /usr/lib/go/src/syscall/zsyscall_linux_amd64.go:503 +0x55
os.(*File).Sync(0xc20fd139a8, 0x0, 0x0)
        /usr/lib/go/src/os/file_posix.go:129 +0x6a
github.com/syndtr/goleveldb/leveldb/storage.fileWrap.Sync(0xc20fd139a8, 0xc20820dee0, 0x0, 0x0)
        /home/bminton/src/hockeypuck/packaging/src/github.com/syndtr/goleveldb/leveldb/storage/file_storage.go:347 +0x3a
github.com/syndtr/goleveldb/leveldb/storage.(*fileWrap).Sync(0xc208783690, 0x0, 0x0)
        <autogenerated>:46 +0xb1
github.com/syndtr/goleveldb/leveldb.(*tWriter).finish(0xc209ae72c0, 0x0, 0x0, 0x0)
        /home/bminton/src/hockeypuck/packaging/src/github.com/syndtr/goleveldb/leveldb/table.go:504 +0x106
github.com/syndtr/goleveldb/leveldb.(*tableCompactionBuilder).flush(0xc20c700a00, 0x0, 0x0)
        /home/bminton/src/hockeypuck/packaging/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:420 +0x55
github.com/syndtr/goleveldb/leveldb.(*tableCompactionBuilder).run(0xc20c700a00, 0xc20c78bc70, 0x0, 0x0)
        /home/bminton/src/hockeypuck/packaging/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:481 +0x986
github.com/syndtr/goleveldb/leveldb.(*DB).compactionTransact(0xc2080e82c0, 0xa7b3d0, 0xb, 0x7fa0ab76f208, 0xc20c700a00)
        /home/bminton/src/hockeypuck/packaging/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:215 +0x277
github.com/syndtr/goleveldb/leveldb.(*DB).tableCompaction(0xc2080e82c0, 0xc20915a000, 0x0)
        /home/bminton/src/hockeypuck/packaging/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:596 +0x10d4
github.com/syndtr/goleveldb/leveldb.(*DB).tableAutoCompaction(0xc2080e82c0)
        /home/bminton/src/hockeypuck/packaging/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:641 +0x50
github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0xc2080e82c0)
        /home/bminton/src/hockeypuck/packaging/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:833 +0x3a0
created by github.com/syndtr/goleveldb/leveldb.openDB
        /home/bminton/src/hockeypuck/packaging/src/github.com/syndtr/goleveldb/leveldb/db.go:130 +0x8a7

goroutine 12 [select, 7 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0xc2080e82c0)
        /home/bminton/src/hockeypuck/packaging/src/github.com/syndtr/goleveldb/leveldb/db_compaction.go:759 +0x283
created by github.com/syndtr/goleveldb/leveldb.openDB
        /home/bminton/src/hockeypuck/packaging/src/github.com/syndtr/goleveldb/leveldb/db.go:131 +0x8c1

goroutine 13 [select, 227 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).jWriter(0xc2080e82c0)
        /home/bminton/src/hockeypuck/packaging/src/github.com/syndtr/goleveldb/leveldb/db_write.go:37 +0x197
created by github.com/syndtr/goleveldb/leveldb.openDB
        /home/bminton/src/hockeypuck/packaging/src/github.com/syndtr/goleveldb/leveldb/db.go:132 +0x8db

goroutine 18 [IO wait]:
net.(*pollDesc).Wait(0xc208011870, 0x72, 0x0, 0x0)
        /usr/lib/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208011870, 0x0, 0x0)
        /usr/lib/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc208011810, 0x0, 0x7fa0ab74ee60, 0xc20c7ea2c8)
        /usr/lib/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc20803acd8, 0xc2098802c8, 0x0, 0x0)
        /usr/lib/go/src/net/tcpsock_posix.go:234 +0x4e
github.com/hockeypuck/server.tcpKeepAliveListener.Accept(0xc20803acd8, 0x0, 0x0, 0x0, 0x0)
        /home/bminton/src/hockeypuck/packaging/src/github.com/hockeypuck/server/server.go:308 +0x4f
net/http.(*Server).Serve(0xc208061920, 0x7fa0ab756408, 0xc20803acd8, 0x0, 0x0)
        /usr/lib/go/src/net/http/server.go:1728 +0x92
net/http.Serve(0x7fa0ab756408, 0xc20803acd8, 0x7fa0ab756440, 0xc2080f2bc0, 0x0, 0x0)
        /usr/lib/go/src/net/http/server.go:1606 +0xa1
github.com/hockeypuck/server.(*Server).listenAndServeHKP(0xc208046090, 0x0, 0x0)
        /home/bminton/src/hockeypuck/packaging/src/github.com/hockeypuck/server/server.go:338 +0x168
github.com/hockeypuck/server.*Server.(github.com/hockeypuck/server.listenAndServeHKP)Â·fm(0x0, 0x0)
        /home/bminton/src/hockeypuck/packaging/src/github.com/hockeypuck/server/server.go:233 +0x39
gopkg.in/tomb%2ev2.(*Tomb).run(0xc2080460d0, 0xc2080e19b0)
        /home/bminton/src/hockeypuck/packaging/src/gopkg.in/tomb.v2/tomb.go:153 +0x24
created by gopkg.in/tomb%2ev2.(*Tomb).Go
        /home/bminton/src/hockeypuck/packaging/src/gopkg.in/tomb.v2/tomb.go:149 +0x119

goroutine 19 [IO wait, 3 minutes]:
net.(*pollDesc).Wait(0xc2100c7f70, 0x72, 0x0, 0x0)
        /usr/lib/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2100c7f70, 0x0, 0x0)
        /usr/lib/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc2100c7f10, 0xc209a53000, 0x1000, 0x1000, 0x0, 0x7fa0ab74ee60, 0xc20b4e9798)
        /usr/lib/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc21037f240, 0xc209a53000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/lib/go/src/net/net.go:121 +0xdc
bufio.(*Reader).fill(0xc2085923c0)
        /usr/lib/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Read(0xc2085923c0, 0xc209af3920, 0x5, 0x200, 0x200, 0x0, 0x0)
        /usr/lib/go/src/bufio/bufio.go:174 +0x26c
io.ReadAtLeast(0x7fa0ab750848, 0xc2085923c0, 0xc209af3920, 0x5, 0x200, 0x5, 0x0, 0x0, 0x0)
        /usr/lib/go/src/io/io.go:298 +0xf1
io.ReadFull(0x7fa0ab750848, 0xc2085923c0, 0xc209af3920, 0x5, 0x200, 0x0, 0x0, 0x0)
        /usr/lib/go/src/io/io.go:316 +0x6d
github.com/lib/pq.(*conn).recvMessage(0xc209af3900, 0xc209af3920, 0x5, 0x0, 0x0)
        /home/bminton/src/hockeypuck/packaging/src/github.com/lib/pq/conn.go:722 +0x124
github.com/lib/pq.(*conn).recv1(0xc209af3900, 0xc209a2b400, 0x5)
        /home/bminton/src/hockeypuck/packaging/src/github.com/lib/pq/conn.go:775 +0x3a
github.com/lib/pq.(*stmt).exec(0xc209015c00, 0xc2094e3220, 0x5, 0x5)
        /home/bminton/src/hockeypuck/packaging/src/github.com/lib/pq/conn.go:1160 +0xb27
github.com/lib/pq.(*stmt).Exec(0xc209015c00, 0xc2094e3220, 0x5, 0x5, 0x0, 0x0, 0x0, 0x0)
        /home/bminton/src/hockeypuck/packaging/src/github.com/lib/pq/conn.go:1102 +0x1cb
github.com/lib/pq.(*conn).Exec(0xc209af3900, 0xb3e1b0, 0x62, 0xc2094e3220, 0x5, 0x5, 0x0, 0x0, 0x0, 0x0)
        /home/bminton/src/hockeypuck/packaging/src/github.com/lib/pq/conn.go:665 +0x25a
database/sql.(*Tx).Exec(0xc2094e3040, 0xb3e1b0, 0x62, 0xc20a84b8d8, 0x5, 0x5, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/go/src/database/sql/sql.go:1231 +0x261
gopkg.in/hockeypuck/pghkp%2ev1.(*storage).Update(0xc2080e4fc0, 0xc2094ca3c0, 0xc209a2a4a0, 0x20, 0x0, 0x0)
        /home/bminton/src/hockeypuck/packaging/src/gopkg.in/hockeypuck/pghkp.v1/storage.go:509 +0x560
gopkg.in/hockeypuck/hkp.v1/storage.UpsertKey(0x7fa0ab750b28, 0xc2080e4fc0, 0xc2094ca000, 0x0, 0x0, 0x0, 0x0)
        /home/bminton/src/hockeypuck/packaging/src/gopkg.in/hockeypuck/hkp.v1/storage/storage.go:211 +0x6ac
gopkg.in/hockeypuck/hkp.v1/sks.(*Peer).upsertKeys(0xc208104200, 0xc209d75000, 0xacb, 0xe00, 0x0, 0x0)
        /home/bminton/src/hockeypuck/packaging/src/gopkg.in/hockeypuck/hkp.v1/sks/recon.go:325 +0x258
gopkg.in/hockeypuck/hkp.v1/sks.(*Peer).requestChunk(0xc208104200, 0xc20a6fb800, 0xc20f542e40, 0x64, 0x2238, 0x0, 0x0)
        /home/bminton/src/hockeypuck/packaging/src/gopkg.in/hockeypuck/hkp.v1/sks/recon.go:305 +0x1178
gopkg.in/hockeypuck/hkp.v1/sks.(*Peer).requestRecovered(0xc208104200, 0xc20a6fb800, 0x0, 0x0)
        /home/bminton/src/hockeypuck/packaging/src/gopkg.in/hockeypuck/hkp.v1/sks/recon.go:228 +0x14f
gopkg.in/hockeypuck/hkp.v1/sks.(*Peer).handleRecovery(0xc208104200, 0x0, 0x0)
        /home/bminton/src/hockeypuck/packaging/src/gopkg.in/hockeypuck/hkp.v1/sks/recon.go:211 +0x13f
gopkg.in/hockeypuck/hkp.v1/sks.*Peer.(gopkg.in/hockeypuck/hkp.v1/sks.handleRecovery)Â·fm(0x0, 0x0)
        /home/bminton/src/hockeypuck/packaging/src/gopkg.in/hockeypuck/hkp.v1/sks/recon.go:148 +0x39
gopkg.in/tomb%2ev2.(*Tomb).run(0xc208104248, 0xc2080e19c0)
        /home/bminton/src/hockeypuck/packaging/src/gopkg.in/tomb.v2/tomb.go:153 +0x24
created by gopkg.in/tomb%2ev2.(*Tomb).Go
        /home/bminton/src/hockeypuck/packaging/src/gopkg.in/tomb.v2/tomb.go:149 +0x119

goroutine 20 [select, 48 minutes]:
gopkg.in/hockeypuck/hkp.v1/sks.(*Peer).pruneStats(0xc208104200, 0x0, 0x0)
        /home/bminton/src/hockeypuck/packaging/src/gopkg.in/hockeypuck/hkp.v1/sks/recon.go:133 +0x193
gopkg.in/hockeypuck/hkp.v1/sks.*Peer.(gopkg.in/hockeypuck/hkp.v1/sks.pruneStats)Â·fm(0x0, 0x0)
        /home/bminton/src/hockeypuck/packaging/src/gopkg.in/hockeypuck/hkp.v1/sks/recon.go:149 +0x39
gopkg.in/tomb%2ev2.(*Tomb).run(0xc208104248, 0xc2080e19d0)
        /home/bminton/src/hockeypuck/packaging/src/gopkg.in/tomb.v2/tomb.go:153 +0x24
created by gopkg.in/tomb%2ev2.(*Tomb).Go
        /home/bminton/src/hockeypuck/packaging/src/gopkg.in/tomb.v2/tomb.go:149 +0x119

goroutine 21 [IO wait, 19 minutes]:
net.(*pollDesc).Wait(0xc2080118e0, 0x72, 0x0, 0x0)
        /usr/lib/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2080118e0, 0x0, 0x0)
        /usr/lib/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc208011880, 0x0, 0x7fa0ab74ee60, 0xc208608b30)
        /usr/lib/go/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc20803acf8, 0x7fa0ab73d000, 0x0, 0x0)
        /usr/lib/go/src/net/tcpsock_posix.go:234 +0x4e
net.(*TCPListener).Accept(0xc20803acf8, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/go/src/net/tcpsock_posix.go:244 +0x4c
gopkg.in/hockeypuck/conflux.v2/recon.(*Peer).Serve(0xc208108380, 0x0, 0x0)
        /home/bminton/src/hockeypuck/packaging/src/gopkg.in/hockeypuck/conflux.v2/recon/peer.go:286 +0x4fa
gopkg.in/hockeypuck/conflux.v2/recon.*Peer.ServeÂ·fm(0x0, 0x0)
        /home/bminton/src/hockeypuck/packaging/src/gopkg.in/hockeypuck/conflux.v2/recon/peer.go:135 +0x39
gopkg.in/tomb%2ev2.(*Tomb).run(0xc2081083a8, 0xc2080e19e0)
        /home/bminton/src/hockeypuck/packaging/src/gopkg.in/tomb.v2/tomb.go:153 +0x24
created by gopkg.in/tomb%2ev2.(*Tomb).Go
        /home/bminton/src/hockeypuck/packaging/src/gopkg.in/tomb.v2/tomb.go:149 +0x119

goroutine 23 [chan receive, 227 minutes]:
main.funcÂ·001()
        /home/bminton/src/hockeypuck/packaging/src/github.com/hockeypuck/server/cmd/hockeypuck/main.go:54 +0x95
created by main.main
        /home/bminton/src/hockeypuck/packaging/src/github.com/hockeypuck/server/cmd/hockeypuck/main.go:66 +0x5e9

goroutine 24 [chan receive, 227 minutes]:
github.com/hockeypuck/server.funcÂ·007(0x0, 0x0)
        /home/bminton/src/hockeypuck/packaging/src/github.com/hockeypuck/server/server.go:326 +0x74
gopkg.in/tomb%2ev2.(*Tomb).run(0xc2080460d0, 0xc208159820)
        /home/bminton/src/hockeypuck/packaging/src/gopkg.in/tomb.v2/tomb.go:153 +0x24
created by gopkg.in/tomb%2ev2.(*Tomb).Go
        /home/bminton/src/hockeypuck/packaging/src/gopkg.in/tomb.v2/tomb.go:149 +0x119

goroutine 25 [chan receive, 227 minutes]:
gopkg.in/hockeypuck/conflux.v2/recon.funcÂ·004(0x0, 0x0)
        /home/bminton/src/hockeypuck/packaging/src/gopkg.in/hockeypuck/conflux.v2/recon/peer.go:281 +0x74
gopkg.in/tomb%2ev2.(*Tomb).run(0xc2081083a8, 0xc20814e1a0)
        /home/bminton/src/hockeypuck/packaging/src/gopkg.in/tomb.v2/tomb.go:153 +0x24
created by gopkg.in/tomb%2ev2.(*Tomb).Go
        /home/bminton/src/hockeypuck/packaging/src/gopkg.in/tomb.v2/tomb.go:149 +0x119

goroutine 193129 [semacquire]:
sync.(*WaitGroup).Wait(0xc2081083d8)
        /usr/lib/go/src/sync/waitgroup.go:132 +0x169
gopkg.in/hockeypuck/conflux.v2/recon.funcÂ·003(0x0, 0x0)
        /home/bminton/src/hockeypuck/packaging/src/gopkg.in/hockeypuck/conflux.v2/recon/peer.go:216 +0x51
gopkg.in/tomb%2ev2.(*Tomb).run(0xc2081083a8, 0xc20c7ea020)
        /home/bminton/src/hockeypuck/packaging/src/gopkg.in/tomb.v2/tomb.go:153 +0x24
created by gopkg.in/tomb%2ev2.(*Tomb).Go
        /home/bminton/src/hockeypuck/packaging/src/gopkg.in/tomb.v2/tomb.go:149 +0x119

goroutine 193130 [runnable]:
net.(*pollDesc).Wait(0xc209458220, 0x72, 0x0, 0x0)
        /usr/lib/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc209458220, 0x0, 0x0)
        /usr/lib/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc2094581c0, 0xc208d2d000, 0x1000, 0x1000, 0x0, 0x7fa0ab74ee60, 0xc20c7eab28)
        /usr/lib/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc21037ec60, 0xc208d2d000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/lib/go/src/net/net.go:121 +0xdc
bufio.(*Reader).fill(0xc2080aaba0)
        /usr/lib/go/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Read(0xc2080aaba0, 0xc209af2020, 0x5, 0x200, 0x200, 0x0, 0x0)
        /usr/lib/go/src/bufio/bufio.go:174 +0x26c
io.ReadAtLeast(0x7fa0ab750848, 0xc2080aaba0, 0xc209af2020, 0x5, 0x200, 0x5, 0x0, 0x0, 0x0)
        /usr/lib/go/src/io/io.go:298 +0xf1
io.ReadFull(0x7fa0ab750848, 0xc2080aaba0, 0xc209af2020, 0x5, 0x200, 0x0, 0x0, 0x0)
        /usr/lib/go/src/io/io.go:316 +0x6d
github.com/lib/pq.(*conn).recvMessage(0xc209af2000, 0xc209af2020, 0x55, 0x0, 0x0)
        /home/bminton/src/hockeypuck/packaging/src/github.com/lib/pq/conn.go:722 +0x124
github.com/lib/pq.(*conn).recv1(0xc209af2000, 0xc20fea99e0, 0x55)
        /home/bminton/src/hockeypuck/packaging/src/github.com/lib/pq/conn.go:775 +0x3a
github.com/lib/pq.(*conn).simpleQuery(0xc209af2000, 0xc2094e20f0, 0x4f, 0x0, 0x0, 0x0, 0x0)
        /home/bminton/src/hockeypuck/packaging/src/github.com/lib/pq/conn.go:503 +0x3e0
github.com/lib/pq.(*conn).Query(0xc209af2000, 0xc2094e20f0, 0x4f, 0xd5a950, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/bminton/src/hockeypuck/packaging/src/github.com/lib/pq/conn.go:630 +0x13a
database/sql.(*DB).queryConn(0xc2080a2fa0, 0xc209ea9f20, 0xc20c7eab90, 0xc2094e20f0, 0x4f, 0x0, 0x0, 0x0, 0xc2094e20f0, 0x0, ...)
        /usr/lib/go/src/database/sql/sql.go:951 +0x1d8
database/sql.(*DB).query(0xc2080a2fa0, 0xc2094e20f0, 0x4f, 0x0, 0x0, 0x0, 0x60, 0x0, 0x0)
        /usr/lib/go/src/database/sql/sql.go:938 +0x135
database/sql.(*DB).Query(0xc2080a2fa0, 0xc2094e20f0, 0x4f, 0x0, 0x0, 0x0, 0x4f, 0x0, 0x0)
        /usr/lib/go/src/database/sql/sql.go:924 +0xa6
gopkg.in/hockeypuck/pghkp%2ev1.(*storage).MatchMD5(0xc2080e4fc0, 0xc20c7eab50, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/bminton/src/hockeypuck/packaging/src/gopkg.in/hockeypuck/pghkp.v1/storage.go:158 +0x5b3
gopkg.in/hockeypuck/hkp%2ev1.(*Handler).HashQuery(0xc208039d40, 0x7fa09bf9fdc8, 0xc209880320, 0xc2087ef380, 0x0, 0x0, 0x0)
        /home/bminton/src/hockeypuck/packaging/src/gopkg.in/hockeypuck/hkp.v1/handler.go:171 +0x23e
gopkg.in/hockeypuck/hkp%2ev1.*Handler.HashQueryÂ·fm(0x7fa09bf9fdc8, 0xc209880320, 0xc2087ef380, 0x0, 0x0, 0x0)
        /home/bminton/src/hockeypuck/packaging/src/gopkg.in/hockeypuck/hkp.v1/handler.go:139 +0x63
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc2080f0bd0, 0x7fa09bf9fdc8, 0xc209880320, 0xc2087ef380)
        /home/bminton/src/hockeypuck/packaging/src/github.com/julienschmidt/httprouter/router.go:298 +0x18e
github.com/carbocation/interpose.funcÂ·002(0x7fa09bf9fdc8, 0xc209880320, 0xc2087ef380)
        /home/bminton/src/hockeypuck/packaging/src/github.com/carbocation/interpose/interpose.go:55 +0x60
net/http.HandlerFunc.ServeHTTP(0xc20c793920, 0x7fa09bf9fdc8, 0xc209880320, 0xc2087ef380)
        /usr/lib/go/src/net/http/server.go:1265 +0x41
github.com/hockeypuck/server.funcÂ·001(0x7fa09bf9fdc8, 0xc209880320, 0xc2087ef380)
        /home/bminton/src/hockeypuck/packaging/src/github.com/hockeypuck/server/server.go:66 +0x9b
net/http.HandlerFunc.ServeHTTP(0xc20c7ea360, 0x7fa09bf9fdc8, 0xc209880320, 0xc2087ef380)
        /usr/lib/go/src/net/http/server.go:1265 +0x41
github.com/carbocation/interpose.(*Middleware).ServeHTTP(0xc2080f2bc0, 0x7fa09bf9fdc8, 0xc209880320, 0xc2087ef380)
        /home/bminton/src/hockeypuck/packaging/src/github.com/carbocation/interpose/interpose.go:85 +0x73
net/http.serverHandler.ServeHTTP(0xc208061920, 0x7fa09bf9fdc8, 0xc209880320, 0xc2087ef380)
        /usr/lib/go/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc209880280)
        /usr/lib/go/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
        /usr/lib/go/src/net/http/server.go:1751 +0x35e

**Comment by bjmgeek** [comment] 2015-08-01 23:23
I thought this was with the latest version from https://github.com/hockeypuck/packaging, but it's possible I got an old version.

**Comment by cmars** [comment] 2015-08-03 21:14
That panic looks like a race that I [fixed in conflux](https://github.com/hockeypuck/conflux/commit/aa90c9a973df4ce6f26a9a8eda5418d35ef647d2) back in May. If you can reproduce it, reopen & send me the git commit hash in /home/bminton/src/hockeypuck/packaging/src/gopkg.in/hockeypuck/conflux.v2.

**Closed by cmars** 2015-08-03 21:14 UTC
